/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Themes', [{
      title: 'Еда - Food',
      img: 'https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2022-03/plant-based-food-mc-220323-02-273c7b.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Транспорт - Transport',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJuFLQN8mseC_m2eSfoLEgERD4hGBwTqQyUw&usqp=CAU',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Знакомство - Meeting',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQPZqH6O9cbtW0kk9oUwHmNfx6sLTuAeB2izEOcK6KHNIYihElNEtC1y7InXPaMPx8NLQ&usqp=CAU',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
    await queryInterface.bulkInsert('Words', [{
      rus: 'Еда',
      eng: 'Food',
      img: 'https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2022-03/plant-based-food-mc-220323-02-273c7b.jpg',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Завтрак',
      eng: 'Breakfast',
      img: 'https://www.restoran.ru/upload/resize_cache/iblock/702/500_334_11a88371ca9e7ba72ce6f5767ba9eff1a/138104_74067nothumb500.jpg',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Ужин',
      eng: 'Dinner',
      img: 'https://img.povar.ru/main-micro/f1/06/3a/17/ujin_bez_myasa-415647.jpg',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Обед',
      eng: 'Lunch',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZuGVd-aJFUqrr7r5h5WBhI4ISPTo-T4GHDw&usqp=CAU',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Закуска',
      eng: 'Snack',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf4va1Lv7qTQ7kRgtyH8JIGYMhm3jZEdCC2d_NT0FaQzTJW9ZugCf36G_THLHdmYCau4c&usqp=CAU',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Десерт',
      eng: 'Dessert',
      img: 'https://www.vkusnyblog.com/wp-content/uploads/2012/07/desert-s-lesnymi-yagodami.jpg',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Овощ',
      eng: 'Vegetable',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDtgwwH7F7uEF3rIuXrBL-_fpGa-JFqlbVAFvolKfEPOPIeZ4xUxxqv8NnYRjGt9uVFDc&usqp=CAU',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Фрукт',
      eng: 'Fruit',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2pUa9jUARVyTBo2t4fUkmFtfclpvjdEvPmg&usqp=CAU',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Мясо',
      eng: 'Meat',
      img: 'https://worldclassmag.com/files/nodus_items/0005/2716/_cache/fit988x988-image-2716-1611310336.jpg',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Рыба',
      eng: 'Fish',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNgQXbtHGenUiisJpY_9B5TAi4rTEcruWBGpLzJNWyZ8Qwz7DF3nlx6Oog7XUiUEOBsK4&usqp=CAU',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Машина',
      eng: 'Car',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiHAsseQmD7lz7CprqSQ1T7hCjVT1aa5Ix6ML8TOS8_4zlqXwhoeF7k78I021Bngjwp0c&usqp=CAU',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Автобус',
      eng: 'Bus',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvlah_1kiW7xGhpBiBD8ppYWddU9DaUdqrVA&usqp=CAU',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Велосипед',
      eng: 'Bicycle',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfR7mL7RagnGmZrva5Fc9P0BU9i8Fo_3CVCy_qKg3E8EPH0zeI1nHtoCDPltd2pF7cRwY&usqp=CAU',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Мотоцикл',
      eng: 'Motorcycle',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTIOtVYrU1l9SPtoxUxW4Ji-p7zImdfpcFpzxzr7VvOET5H7pg2ufK9vj0OnuEBKjqkZw&usqp=CAU',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Самолет',
      eng: 'Plane',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8qZdUdDTZ2DuxLk2ujwRTluCiQP-j_rrBE1A1kH4YnQvkuhhYZE0t4eYtKKt3xeX69zw&usqp=CAU',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Лодка',
      eng: 'Boat',
      img: 'https://thumb.tildacdn.com/tild3766-6236-4635-a535-666464633864/-/resize/600x/-/format/webp/S-open_min.png',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Метро',
      eng: 'Subway',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Saint_Petersburg_metro_future_map_RUS.png/1200px-Saint_Petersburg_metro_future_map_RUS.png',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Такси',
      eng: 'Taxi',
      img: 'https://vop.ru/sites/default/files/styles/raw/public/images/1566396656_taxi-5-film.jpg?itok=dM9ksgvk',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Трамвай',
      eng: 'Tram',
      img: 'https://apps3proxy.mosmetro.tech/2_6.jpg',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Поезд',
      eng: 'Train',
      img: 'https://tlt.ru/wp-content/uploads/2022/01/Qt2CJrvoUmc.jpg',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Привет',
      eng: 'Hello',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBqeN-k4_iJHeI0vscl_RA-7cM8oXyEC_QDMRDaSBXAPfzQFPOQ4eqeZDH2zzN83R8THM&usqp=CAU',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Пока',
      eng: 'Goodbye',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfDKjYyNizYfbBxKoT6MeStoFGZWCUMopyg3aCmSQjZZaOHBUPSYs-mrcKH6notrB70HE&usqp=CAU',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Рад знакомству',
      eng: 'Nice to meet you',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIVEfeNnidm5jF5s2ILfBCHq8SZ9NF75yjzdrMWRaKaySUxrC5tw-gq3bHt6WBPOZJ5Cs&usqp=CAU',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Как дела?',
      eng: 'How are you?',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlDvzo5bunU8Ot_vHaJVGeE4oqFqfHoSb_sfDjr59cvMYR2-CjHSGvwaapqqZxfyErACc&usqp=CAU',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Как вас зовут?',
      eng: "What's your name?",
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2VKCSZdeyAZss5pS1kN-MYTVDStgKXJI3Nw&usqp=CAU',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Меня зовут...',
      eng: 'My name is..',
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKCn8RDKKqywMKests_pAaikG_NAHdAX5smJoXctk6Foi0350bOQYUOEjsgKdrro7oF7k&usqp=CAU',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Откуда вы?',
      eng: 'Where are you from?',
      img: 'http://risovach.ru/upload/2013/06/mem/moe-lico_22270521_orig_.jpeg',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Я из...',
      eng: "I'm from...",
      img: 'https://cont.ws/uploads/pic/2020/7/rossiya-strana-benzokolonka.jpg',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Говорите ли вы по-английски?',
      eng: 'Do you speak English?',
      img: 'https://cdn0.youla.io/files/images/orig/62/37/623797b2461b35334430d619-1.jpg',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      rus: 'Да',
      eng: 'Yes',
      img: 'https://sun9-59.userapi.com/impg/c854324/v854324672/251d3f/PfpD1TmQwaE.jpg?size=414x604&quality=96&sign=67fd96fa561e8163599d06605aa2f981&c_uniq_tag=PJmtlS2iAzZfLgM2BZGWRBI3TTX3aa5--PhOCWF-lyY&type=album',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Themes', null, {});
    await queryInterface.bulkDelete('Words', null, {});
  },
};
